Rails.application.routes.draw do
  get 'people/delete/:id',to:'people#delete'
  get 'people/edit/:id',to:'people#edit'
  post 'people/edit/:id',to:'people#update'
  patch 'people/edit/:id',to:'people#update'
  get 'people/add'
  post 'people/add',to:'people#create'
  get 'people/index'
  get 'people',to:'people#index'
  get 'people/:id',to:'people#show'
  get'dengonban',to:'dengonban#index'
  post'dengonban',to:'dengonban#index'
  get 'dengonban/index'
  post'dengonban/index'
  get 'helo/index'
  get 'helo',to:'helo#index'
  get 'helo/other'
  post'helo',to:'helo#index'
  post'helo/index'
end
