# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 48130676254cbf7d1e0f76de34a1f921fd95c0708fd8166b010485cf095403d232d4a73e81091ae3dd89bf3fdd319e3ba8cc793b7e2403335cc4a3734ba8b000

test:
  secret_key_base: d3f294d5ed6f91dd90787545d3d092706fbfd97ea12cd8d01da90899320425b40de0446fe9446ccba345ec74852b7997e57d01b1cf995606ddfd3c61a6cf915a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
